//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solitaire.I18n {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Solitaire.I18n.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string app_name {
            get {
                return ResourceManager.GetString("app.name", resourceCulture);
            }
        }
        
        internal static string createdby {
            get {
                return ResourceManager.GetString("createdby", resourceCulture);
            }
        }
        
        internal static string option_play {
            get {
                return ResourceManager.GetString("option.play", resourceCulture);
            }
        }
        
        internal static string option_quit {
            get {
                return ResourceManager.GetString("option.quit", resourceCulture);
            }
        }
        
        internal static string difficulty_label {
            get {
                return ResourceManager.GetString("difficulty.label", resourceCulture);
            }
        }
        
        internal static string difficulty_easy {
            get {
                return ResourceManager.GetString("difficulty.easy", resourceCulture);
            }
        }
        
        internal static string difficulty_hard {
            get {
                return ResourceManager.GetString("difficulty.hard", resourceCulture);
            }
        }
        
        internal static string game_selectedcard_label {
            get {
                return ResourceManager.GetString("game.selectedcard.label", resourceCulture);
            }
        }
        
        internal static string game_foundations {
            get {
                return ResourceManager.GetString("game.foundations", resourceCulture);
            }
        }
        
        internal static string game_stock_label {
            get {
                return ResourceManager.GetString("game.stock.label", resourceCulture);
            }
        }
        
        internal static string game_waste_label {
            get {
                return ResourceManager.GetString("game.waste.label", resourceCulture);
            }
        }
        
        internal static string language_label {
            get {
                return ResourceManager.GetString("language.label", resourceCulture);
            }
        }
        
        internal static string win_label {
            get {
                return ResourceManager.GetString("win.label", resourceCulture);
            }
        }
        
        internal static string move_count_label {
            get {
                return ResourceManager.GetString("move.count.label", resourceCulture);
            }
        }
    }
}
